services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: haibazo_api
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-root}:${POSTGRES_PASSWORD:-123456}@db:5432/${POSTGRES_DB:-book_review_db}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  db:
    image: postgres:17-alpine
    container_name: haibazo_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-book_review_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-root} -d ${POSTGRES_DB:-book_review_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: